// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezjpvpnadwitzbybjwfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6anB2cG5hZHdpdHpieWJqd2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjgzNzUsImV4cCI6MjA2MjE0NDM3NX0.32HEVWa4SA2DszPbJwwhd1M0NGu-nmXe-gQHhcgGm2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);